
# Setting PATH for Python 3.5
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.5/bin:${PATH}"
export PATH
alias ll='ls -l'
alias la='ls -al'
alias emacs="/usr/local/Cellar/emacs/26.1_1/Emacs.app/Contents/MacOS/Emacs -nw"
PATH=$PATH:/usr/local/mysql/bin

PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.5/bin

export JAVA_HOME=$(/usr/libexec/java_home)
export CLASS_PATH="$JAVA_HOME/lib" 
export PATH=".;$PATH:$JAVA_HOME/bin"
